# fly.toml app configuration file generated for praxis-ai on 2025-08-19T12:21:30Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "praxis-ai"
primary_region = "bom"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "120s"   # Increased to 2 minutes for AI model loading
    interval = "30s"        # Check every 30 seconds instead of 15
    timeout = "30s"         # Increased timeout for health check response
    method = "GET"
    path = "/health"        # Use the /health endpoint for health checks
    port = 8080             # Specify the port for health checks

[[vm]]
  memory = "4gb"           # Increased memory for AI/ML workloads
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 4096


