# fly.toml app configuration file generated for praxis-ai on 2025-08-19T12:21:30Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "praxis-ai"
primary_region = "bom"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"   # allow 10 seconds before health checks start, adjust if your app needs longer to start
    interval = "10s"       # check every 10 seconds
    timeout = "3s"         # health check must respond within 3 seconds
    method = "GET"
    path = "/health"       # use the /health endpoint for health checks

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

