import csv
import os

def populate_all_chapters():
    """Populate the CSV with all chapters and their topics."""
    
    # All chapters with their topics
    all_chapters = [
        # Chemistry Class 11
        {
            'subject': 'Chemistry',
            'class': 'Class 11',
            'chapter_file': 'Some Basic Concepts Of Chemistry.pdf',
            'chapter_number': '1',
            'headings': [
                ("1", "Some Basic Concepts of Chemistry"),
                ("1.1", "Importance of Chemistry"),
                ("1.2", "Nature of Matter"),
                ("1.3", "Properties of Matter and their Measurement"),
                ("1.4", "Uncertainty in Measurement"),
                ("1.5", "Laws of Chemical Combinations"),
                ("1.6", "Dalton's Atomic Theory"),
                ("1.7", "Atomic and Molecular Masses"),
                ("1.8", "Mole Concept and Molar Masses"),
                ("1.9", "Percentage Composition"),
                ("1.10", "Stoichiometry and Stoichiometric Calculations"),
                ("1.1.1", "Physical Quantities"),
                ("1.1.2", "Units"),
                ("1.1.3", "Base Units"),
                ("1.1.4", "Derived Units"),
                ("1.2.1", "States of Matter"),
                ("1.2.2", "Classification of Matter"),
                ("1.2.3", "Properties of Matter"),
                ("1.3.1", "Measurement of Mass"),
                ("1.3.2", "Measurement of Volume"),
                ("1.3.3", "Measurement of Temperature"),
                ("1.4.1", "Significant Figures"),
                ("1.4.2", "Precision and Accuracy"),
                ("1.4.3", "Errors in Measurement"),
                ("1.5.1", "Law of Conservation of Mass"),
                ("1.5.2", "Law of Definite Proportions"),
                ("1.5.3", "Law of Multiple Proportions"),
                ("1.5.4", "Gay Lussac's Law of Gaseous Volumes"),
                ("1.5.5", "Avogadro's Law"),
                ("1.6.1", "Postulates of Dalton's Atomic Theory"),
                ("1.6.2", "Limitations of Dalton's Atomic Theory"),
                ("1.7.1", "Atomic Mass"),
                ("1.7.2", "Molecular Mass"),
                ("1.7.3", "Formula Mass"),
                ("1.8.1", "Mole Concept"),
                ("1.8.2", "Molar Mass"),
                ("1.8.3", "Molar Volume"),
                ("1.9.1", "Percentage by Mass"),
                ("1.9.2", "Percentage by Volume"),
                ("1.10.1", "Stoichiometric Calculations"),
                ("1.10.2", "Limiting Reagent"),
                ("1.10.3", "Reactions in Solutions"),
            ]
        },
        {
            'subject': 'Chemistry',
            'class': 'Class 11',
            'chapter_file': 'Structure Of Atom.pdf',
            'chapter_number': '2',
            'headings': [
                ("2", "Structure of Atom"),
                ("2.1", "Discovery of Sub-atomic Particles"),
                ("2.2", "Atomic Models"),
                ("2.3", "Developments Leading to the Bohr's Model of Atom"),
                ("2.4", "Bohr's Model for Hydrogen Atom"),
                ("2.5", "Towards Quantum Mechanical Model of the Atom"),
                ("2.6", "Quantum Mechanical Model of Atom"),
                ("2.1.1", "Discovery of Electron"),
                ("2.1.2", "Discovery of Proton"),
                ("2.1.3", "Discovery of Neutron"),
                ("2.1.4", "Charge to Mass Ratio of Electron"),
                ("2.1.5", "Charge on Electron"),
                ("2.1.6", "Mass of Electron"),
                ("2.2.1", "Thomson's Model of Atom"),
                ("2.2.2", "Rutherford's Model of Atom"),
                ("2.2.3", "Limitations of Rutherford's Model"),
                ("2.3.1", "Wave Nature of Electromagnetic Radiation"),
                ("2.3.2", "Particle Nature of Electromagnetic Radiation: Planck's Quantum Theory"),
                ("2.3.3", "Photoelectric Effect"),
                ("2.3.4", "Emission and Absorption Spectra"),
                ("2.3.5", "Line Spectrum of Hydrogen"),
                ("2.3.6", "Bohr's Model for Hydrogen Atom"),
                ("2.4.1", "Energy of Electron in Bohr's Orbits"),
                ("2.4.2", "Limitations of Bohr's Model"),
                ("2.4.3", "Towards Quantum Mechanical Model"),
                ("2.5.1", "Dual Behaviour of Matter"),
                ("2.5.2", "Heisenberg's Uncertainty Principle"),
                ("2.5.3", "Quantum Mechanical Model of Atom"),
                ("2.6.1", "Orbitals and Quantum Numbers"),
                ("2.6.2", "Shapes of Atomic Orbitals"),
                ("2.6.3", "Energies of Orbitals"),
                ("2.6.4", "Filling of Orbitals in Atoms"),
                ("2.6.5", "Electronic Configuration of Atoms"),
                ("2.6.6", "Stability of Completely Filled and Half Filled Subshells"),
            ]
        },
        {
            'subject': 'Chemistry',
            'class': 'Class 11',
            'chapter_file': 'Classification Of Elements And Periodicity.pdf',
            'chapter_number': '3',
            'headings': [
                ("3", "Classification of Elements and Periodicity in Properties"),
                ("3.1", "Why do we need to classify elements?"),
                ("3.2", "Genesis of Periodic Classification"),
                ("3.3", "Modern Periodic Law and the present form of the Periodic Table"),
                ("3.4", "Nomenclature of Elements with Atomic Numbers > 100"),
                ("3.5", "Electronic Configurations of Elements and the Periodic Table"),
                ("3.6", "Electronic Configurations and Types of Elements: s-, p-, d-, f- Blocks"),
                ("3.7", "Periodic Trends in Properties of Elements"),
                ("3.1.1", "Need for Classification"),
                ("3.1.2", "Early Attempts at Classification"),
                ("3.2.1", "Dobereiner's Triads"),
                ("3.2.2", "Newlands' Law of Octaves"),
                ("3.2.3", "Mendeleev's Periodic Table"),
                ("3.2.4", "Achievements of Mendeleev's Periodic Table"),
                ("3.2.5", "Limitations of Mendeleev's Periodic Table"),
                ("3.3.1", "Modern Periodic Law"),
                ("3.3.2", "Long Form of Periodic Table"),
                ("3.3.3", "Features of Long Form of Periodic Table"),
                ("3.4.1", "Naming of Elements"),
                ("3.4.2", "Symbols of Elements"),
                ("3.5.1", "Electronic Configuration and Periodic Table"),
                ("3.5.2", "Periodic Table and Electronic Configuration"),
                ("3.6.1", "s-Block Elements"),
                ("3.6.2", "p-Block Elements"),
                ("3.6.3", "d-Block Elements"),
                ("3.6.4", "f-Block Elements"),
                ("3.7.1", "Atomic Radius"),
                ("3.7.2", "Ionic Radius"),
                ("3.7.3", "Ionization Enthalpy"),
                ("3.7.4", "Electron Gain Enthalpy"),
                ("3.7.5", "Electronegativity"),
                ("3.7.6", "Valency"),
                ("3.7.7", "Metallic and Non-metallic Character"),
                ("3.7.8", "Nature of Oxides"),
                ("3.7.9", "Nature of Hydrides"),
                ("3.7.10", "Nature of Halides"),
            ]
        },
        {
            'subject': 'Chemistry',
            'class': 'Class 11',
            'chapter_file': 'Chemical Bonding And Molecular Structure.pdf',
            'chapter_number': '4',
            'headings': [
                ("4", "KÖssel-Lewis Approach to Chemical Bonding"),
                ("4.1", "Ionic or Electrovalent Bond"),
                ("4.2", "Bond Parameters"),
                ("4.3", "The Valence Shell Electron Pair Repulsion (VSEPR) Theory"),
                ("4.4", "Valence Bond Theory"),
                ("4.5", "Hybridisation"),
                ("4.6", "Molecular Orbital Theory"),
                ("4.7", "Bonding in Some Homonuclear Diatomic Molecules"),
                ("4.8", "Hydrogen Bonding"),
                ("4.1.1", "Octet Rule"),
                ("4.1.2", "Covalent Bond"),
                ("4.1.3", "Lewis Representation of Simple Molecules"),
                ("4.1.4", "Formal Charge"),
                ("4.1.5", "Limitations of the Octet Rule"),
                ("4.2.1", "Lattice Enthalpy"),
                ("4.3.1", "Bond Length"),
                ("4.3.2", "Bond Angle"),
                ("4.3.3", "Bond Enthalpy"),
                ("4.3.4", "Bond Order"),
                ("4.3.5", "Resonance Structures"),
                ("4.3.6", "Polarity of Bonds"),
                ("4.4.1", "Valence Bond Theory Introduction"),
                ("4.4.2", "Overlap of Atomic Orbitals"),
                ("4.5.1", "Orbital Overlap Concept"),
                ("4.5.2", "Directional Properties of Bonds"),
                ("4.5.3", "Overlapping of Atomic Orbitals"),
                ("4.5.4", "Types of Overlapping and Nature of Covalent Bonds"),
                ("4.5.5", "Strength of Sigma and pi Bonds"),
                ("4.6.1", "Types of Hybridisation"),
                ("4.6.2", "Other Examples of sp3, sp2 and sp Hybridisation"),
                ("4.6.3", "Hybridisation of Elements involving d Orbitals"),
                ("4.7.1", "Formation of Molecular Orbitals"),
                ("4.7.2", "Conditions for the Combination of Atomic Orbitals"),
                ("4.7.3", "Types of Molecular Orbitals"),
                ("4.7.4", "Energy Level Diagram for Molecular Orbitals"),
                ("4.7.5", "Electronic Configuration and Molecular Behaviour"),
                ("4.8.1", "Intermolecular Forces"),
                ("4.8.2", "Types of Intermolecular Forces"),
                ("4.9.1", "Cause of Formation of Hydrogen Bond"),
                ("4.9.2", "Types of H-Bonds"),
                ("4.1.1.1", "Octet Rule Explanation"),
                ("4.1.1.2", "Exceptions to Octet Rule"),
                ("4.1.2.1", "Single Covalent Bond"),
                ("4.1.2.2", "Double Covalent Bond"),
                ("4.1.2.3", "Triple Covalent Bond"),
                ("4.1.3.1", "Lewis Dot Structures"),
                ("4.1.3.2", "Lewis Structures for Simple Molecules"),
                ("4.1.4.1", "Calculation of Formal Charge"),
                ("4.1.4.2", "Importance of Formal Charge"),
                ("4.1.5.1", "Incomplete Octet"),
                ("4.1.5.2", "Expanded Octet"),
                ("4.1.5.3", "Odd Electron Molecules"),
                ("4.2.1.1", "Definition of Lattice Enthalpy"),
                ("4.2.1.2", "Factors Affecting Lattice Enthalpy"),
                ("4.3.1.1", "Definition of Bond Length"),
                ("4.3.1.2", "Factors Affecting Bond Length"),
                ("4.3.2.1", "Definition of Bond Angle"),
                ("4.3.2.2", "Factors Affecting Bond Angle"),
                ("4.3.3.1", "Definition of Bond Enthalpy"),
                ("4.3.3.2", "Factors Affecting Bond Enthalpy"),
                ("4.3.4.1", "Definition of Bond Order"),
                ("4.3.4.2", "Calculation of Bond Order"),
                ("4.3.5.1", "Resonance Structures"),
                ("4.3.5.2", "Resonance Hybrid"),
                ("4.3.6.1", "Polar Bonds"),
                ("4.3.6.2", "Non-polar Bonds"),
                ("4.4.1.1", "Valence Bond Theory Basics"),
                ("4.4.1.2", "Postulates of VBT"),
                ("4.4.2.1", "Sigma Bond Formation"),
                ("4.4.2.2", "Pi Bond Formation"),
                ("4.5.1.1", "Orbital Overlap Concept"),
                ("4.5.1.2", "Types of Overlap"),
                ("4.5.2.1", "Directional Properties"),
                ("4.5.2.2", "Bond Directionality"),
                ("4.5.3.1", "s-s Overlap"),
                ("4.5.3.2", "s-p Overlap"),
                ("4.5.3.3", "p-p Overlap"),
                ("4.5.4.1", "Head-on Overlap"),
                ("4.5.4.2", "Sideways Overlap"),
                ("4.5.5.1", "Sigma Bond Strength"),
                ("4.5.5.2", "Pi Bond Strength"),
                ("4.6.1.1", "sp Hybridisation"),
                ("4.6.1.2", "sp2 Hybridisation"),
                ("4.6.1.3", "sp3 Hybridisation"),
                ("4.6.2.1", "sp3 Hybridisation Examples"),
                ("4.6.2.2", "sp2 Hybridisation Examples"),
                ("4.6.2.3", "sp Hybridisation Examples"),
                ("4.6.3.1", "dsp2 Hybridisation"),
                ("4.6.3.2", "dsp3 Hybridisation"),
                ("4.6.3.3", "d2sp3 Hybridisation"),
                ("4.7.1.1", "Formation of Molecular Orbitals"),
                ("4.7.1.2", "Linear Combination of Atomic Orbitals"),
                ("4.7.2.1", "Conditions for Combination"),
                ("4.7.2.2", "Energy Level Matching"),
                ("4.7.3.1", "Bonding Molecular Orbitals"),
                ("4.7.3.2", "Antibonding Molecular Orbitals"),
                ("4.7.4.1", "Energy Level Diagrams"),
                ("4.7.4.2", "Molecular Orbital Energy Levels"),
                ("4.7.5.1", "Electronic Configuration"),
                ("4.7.5.2", "Molecular Behaviour"),
                ("4.8.1.1", "Intermolecular Forces"),
                ("4.8.1.2", "Types of Intermolecular Forces"),
                ("4.8.2.1", "London Dispersion Forces"),
                ("4.8.2.2", "Dipole-Dipole Forces"),
                ("4.8.2.3", "Hydrogen Bonding"),
                ("4.9.1.1", "Cause of Hydrogen Bond Formation"),
                ("4.9.1.2", "Conditions for Hydrogen Bonding"),
                ("4.9.2.1", "Intermolecular Hydrogen Bonding"),
                ("4.9.2.2", "Intramolecular Hydrogen Bonding"),
            ]
        },
        {
            'subject': 'Chemistry',
            'class': 'Class 11',
            'chapter_file': 'Thermodynamics.pdf',
            'chapter_number': '6',
            'headings': [
                ("6", "Thermodynamics"),
                ("6.1", "Thermodynamic Terms"),
                ("6.2", "Applications"),
                ("6.3", "Measurement of ΔU and ΔH: Calorimetry"),
                ("6.4", "Enthalpy Change, ΔrH of a Reaction – Reaction Enthalpy"),
                ("6.5", "Enthalpies for Different Types of Reactions"),
                ("6.6", "Spontaneity"),
                ("6.7", "Gibbs Energy Change and Equilibrium"),
                ("6.1.1", "System and Surroundings"),
                ("6.1.2", "Types of Systems"),
                ("6.1.3", "State Functions"),
                ("6.1.4", "Path Functions"),
                ("6.1.5", "Internal Energy"),
                ("6.1.6", "Enthalpy"),
                ("6.2.1", "Work"),
                ("6.2.2", "Heat"),
                ("6.2.3", "First Law of Thermodynamics"),
                ("6.3.1", "Calorimetry"),
                ("6.3.2", "Measurement of ΔU"),
                ("6.3.3", "Measurement of ΔH"),
                ("6.4.1", "Reaction Enthalpy"),
                ("6.4.2", "Standard Enthalpy of Reaction"),
                ("6.5.1", "Enthalpy of Formation"),
                ("6.5.2", "Enthalpy of Combustion"),
                ("6.5.3", "Enthalpy of Neutralization"),
                ("6.5.4", "Enthalpy of Solution"),
                ("6.6.1", "Spontaneous Processes"),
                ("6.6.2", "Entropy"),
                ("6.6.3", "Second Law of Thermodynamics"),
                ("6.7.1", "Gibbs Energy"),
                ("6.7.2", "Gibbs Energy Change"),
                ("6.7.3", "Equilibrium and Gibbs Energy"),
            ]
        },
        {
            'subject': 'Chemistry',
            'class': 'Class 11',
            'chapter_file': 'Equilibrium.pdf',
            'chapter_number': '7',
            'headings': [
                ("7", "Equilibrium"),
                ("7.1", "Equilibrium in Physical Processes"),
                ("7.2", "Equilibrium in Chemical Processes – Dynamic Equilibrium"),
                ("7.3", "Law of Chemical Equilibrium and Equilibrium Constant"),
                ("7.4", "Heterogeneous Equilibria"),
                ("7.5", "Applications of Equilibrium Constants"),
                ("7.6", "Factors Affecting Equilibria"),
                ("7.7", "Ionic Equilibrium in Solution"),
                ("7.8", "Ionization of Acids and Bases"),
                ("7.9", "Buffer Solutions"),
                ("7.10", "Solubility Equilibria of Sparingly Soluble Salts"),
            ]
        },
        {
            'subject': 'Chemistry',
            'class': 'Class 11',
            'chapter_file': 'Redox Reactions.pdf',
            'chapter_number': '8',
            'headings': [
                ("8", "Redox Reactions"),
                ("8.1", "Classical Idea of Redox Reactions-Oxidation and Reduction Reactions"),
                ("8.2", "Redox Reactions in Terms of Electron Transfer Reactions"),
                ("8.3", "Competitive Electron Transfer Reactions"),
                ("8.4", "Oxidation Number"),
                ("8.5", "Types of Redox Reactions"),
                ("8.6", "Balancing of Redox Reactions"),
                ("8.7", "Redox Reactions as the Basis for Titrations"),
                ("8.8", "Limitations of Concept of Oxidation Number"),
            ]
        },
        {
            'subject': 'Chemistry',
            'class': 'Class 11',
            'chapter_file': 'Hydrocarbons.pdf',
            'chapter_number': '13',
            'headings': [
                ("13", "Hydrocarbons"),
                ("13.1", "Classification"),
                ("13.2", "Alkanes"),
                ("13.3", "Alkenes"),
                ("13.4", "Alkynes"),
                ("13.5", "Aromatic Hydrocarbon"),
                ("13.6", "Carcinogenicity and Toxicity"),
            ]
        },
        {
            'subject': 'Chemistry',
            'class': 'Class 11',
            'chapter_file': 'Organic Chemistry Basics.pdf',
            'chapter_number': '12',
            'headings': [
                ("12", "Organic Chemistry – Some Basic Principles and Techniques"),
                ("12.1", "General Introduction"),
                ("12.2", "Tetravalence of Carbon: Shapes of Organic Compounds"),
                ("12.3", "Structural Representations of Organic Compounds"),
                ("12.4", "Classification of Organic Compounds"),
                ("12.5", "Nomenclature of Organic Compounds"),
                ("12.6", "Isomerism"),
                ("12.7", "Fundamental Concepts in Organic Reaction Mechanism"),
                ("12.8", "Methods of Purification of Organic Compounds"),
                ("12.9", "Qualitative Analysis of Organic Compounds"),
                ("12.10", "Quantitative Analysis"),
            ]
        },
        
        # Physics Class 11
        {
            'subject': 'Physics',
            'class': 'Class 11',
            'chapter_file': 'Units And Measurements.pdf',
            'chapter_number': '2',
            'headings': [
                ("2", "Units and Measurements"),
                ("2.1", "Introduction"),
                ("2.2", "The International System of Units"),
                ("2.3", "Measurement of Length"),
                ("2.4", "Measurement of Mass"),
                ("2.5", "Measurement of Time"),
                ("2.6", "Accuracy, Precision of Instruments and Errors in Measurement"),
                ("2.7", "Significant Figures"),
                ("2.8", "Dimensions of Physical Quantities"),
                ("2.9", "Dimensional Formulae and Dimensional Equations"),
                ("2.10", "Dimensional Analysis and its Applications"),
            ]
        },
        {
            'subject': 'Physics',
            'class': 'Class 11',
            'chapter_file': 'Motion In A Straight Line.pdf',
            'chapter_number': '3',
            'headings': [
                ("3", "Motion in a Straight Line"),
                ("3.1", "Introduction"),
                ("3.2", "Position, Path Length and Displacement"),
                ("3.3", "Average Velocity and Average Speed"),
                ("3.4", "Instantaneous Velocity and Speed"),
                ("3.5", "Acceleration"),
                ("3.6", "Kinematic Equations for Uniformly Accelerated Motion"),
                ("3.7", "Relative Velocity"),
            ]
        },
        {
            'subject': 'Physics',
            'class': 'Class 11',
            'chapter_file': 'Motion In A Plane.pdf',
            'chapter_number': '4',
            'headings': [
                ("4", "Motion in a Plane"),
                ("4.1", "Introduction"),
                ("4.2", "Scalars and Vectors"),
                ("4.3", "Multiplication of Vectors by Real Numbers"),
                ("4.4", "Addition and Subtraction of Vectors – Graphical Method"),
                ("4.5", "Resolution of Vectors"),
                ("4.6", "Vector Addition – Analytical Method"),
                ("4.7", "Motion in a Plane"),
                ("4.8", "Motion in a Plane with Constant Acceleration"),
                ("4.9", "Relative Velocity in Two Dimensions"),
                ("4.10", "Projectile Motion"),
                ("4.11", "Uniform Circular Motion"),
            ]
        },
        {
            'subject': 'Physics',
            'class': 'Class 11',
            'chapter_file': 'Laws Of Motion.pdf',
            'chapter_number': '5',
            'headings': [
                ("5", "Laws of Motion"),
                ("5.1", "Introduction"),
                ("5.2", "Aristotle's Fallacy"),
                ("5.3", "The Law of Inertia"),
                ("5.4", "Newton's First Law of Motion"),
                ("5.5", "Newton's Second Law of Motion"),
                ("5.6", "Newton's Third Law of Motion"),
                ("5.7", "Conservation of Momentum"),
                ("5.8", "Equilibrium of a Particle"),
                ("5.9", "Common Forces in Mechanics"),
                ("5.10", "Circular Motion"),
                ("5.11", "Solving Problems in Mechanics"),
            ]
        },
        {
            'subject': 'Physics',
            'class': 'Class 11',
            'chapter_file': 'Work Energy Power.pdf',
            'chapter_number': '6',
            'headings': [
                ("6", "Work, Energy and Power"),
                ("6.1", "Introduction"),
                ("6.2", "Notions of Work and Kinetic Energy: The Work-Energy Theorem"),
                ("6.3", "Work"),
                ("6.4", "Kinetic Energy"),
                ("6.5", "Work Done by a Variable Force"),
                ("6.6", "The Work-Energy Theorem for a Variable Force"),
                ("6.7", "The Concept of Potential Energy"),
                ("6.8", "The Conservation of Mechanical Energy"),
                ("6.9", "The Potential Energy of a Spring"),
                ("6.10", "Various Forms of Energy: The Law of Conservation of Energy"),
                ("6.11", "Power"),
                ("6.12", "Collisions"),
            ]
        },
        
        # Maths Class 11
        {
            'subject': 'Maths',
            'class': 'Class 11',
            'chapter_file': 'Sets.pdf',
            'chapter_number': '1',
            'headings': [
                ("1", "Sets"),
                ("1.1", "Introduction"),
                ("1.2", "Sets and their Representations"),
                ("1.3", "The Empty Set"),
                ("1.4", "Finite and Infinite Sets"),
                ("1.5", "Equal Sets"),
                ("1.6", "Subsets"),
                ("1.7", "Power Set"),
                ("1.8", "Universal Set"),
                ("1.9", "Venn Diagrams"),
                ("1.10", "Operations on Sets"),
                ("1.11", "Complement of a Set"),
                ("1.12", "Practical Problems on Union and Intersection of Two Sets"),
            ]
        },
        {
            'subject': 'Maths',
            'class': 'Class 11',
            'chapter_file': 'Relations And Functions.pdf',
            'chapter_number': '2',
            'headings': [
                ("2", "Relations and Functions"),
                ("2.1", "Introduction"),
                ("2.2", "Cartesian Products of Sets"),
                ("2.3", "Relations"),
                ("2.4", "Functions"),
            ]
        },
        {
            'subject': 'Maths',
            'class': 'Class 11',
            'chapter_file': 'Trigonometric Functions.pdf',
            'chapter_number': '3',
            'headings': [
                ("3", "Trigonometric Functions"),
                ("3.1", "Introduction"),
                ("3.2", "Angles"),
                ("3.3", "Trigonometric Functions"),
                ("3.4", "Trigonometric Functions of Sum and Difference of Two Angles"),
                ("3.5", "Trigonometric Equations"),
            ]
        },
        {
            'subject': 'Maths',
            'class': 'Class 11',
            'chapter_file': 'Complex Numbers And Quadratic Equations.pdf',
            'chapter_number': '5',
            'headings': [
                ("5", "Complex Numbers and Quadratic Equations"),
                ("5.1", "Introduction"),
                ("5.2", "Complex Numbers"),
                ("5.3", "Algebra of Complex Numbers"),
                ("5.4", "The Modulus and the Conjugate of a Complex Number"),
                ("5.5", "Argand Plane and Polar Representation"),
                ("5.6", "Quadratic Equations"),
            ]
        },
        {
            'subject': 'Maths',
            'class': 'Class 11',
            'chapter_file': 'Linear Inequalities.pdf',
            'chapter_number': '6',
            'headings': [
                ("6", "Linear Inequalities"),
                ("6.1", "Introduction"),
                ("6.2", "Inequalities"),
                ("6.3", "Algebraic Solutions of Linear Inequalities in One Variable and their Graphical Representation"),
                ("6.4", "Graphical Solution of Linear Inequalities in Two Variables"),
                ("6.5", "Solution of System of Linear Inequalities in Two Variables"),
            ]
        },
        {
            'subject': 'Maths',
            'class': 'Class 11',
            'chapter_file': 'Permutations And Combinations.pdf',
            'chapter_number': '7',
            'headings': [
                ("7", "Permutations and Combinations"),
                ("7.1", "Introduction"),
                ("7.2", "Fundamental Principle of Counting"),
                ("7.3", "Permutations"),
                ("7.4", "Combinations"),
            ]
        },
        {
            'subject': 'Maths',
            'class': 'Class 11',
            'chapter_file': 'Binomial Theorem.pdf',
            'chapter_number': '8',
            'headings': [
                ("8", "Binomial Theorem"),
                ("8.1", "Introduction"),
                ("8.2", "Binomial Theorem for Positive Integral Indices"),
                ("8.3", "General and Middle Terms"),
            ]
        },
        {
            'subject': 'Maths',
            'class': 'Class 11',
            'chapter_file': 'Sequences And Series.pdf',
            'chapter_number': '9',
            'headings': [
                ("9", "Sequences and Series"),
                ("9.1", "Introduction"),
                ("9.2", "Sequences"),
                ("9.3", "Series"),
                ("9.4", "Arithmetic Progression (A.P.)"),
                ("9.5", "Geometric Progression (G.P.)"),
                ("9.6", "Relationship Between A.M. and G.M."),
                ("9.7", "Sum to n terms of Special Series"),
            ]
        },
        {
            'subject': 'Maths',
            'class': 'Class 11',
            'chapter_file': 'Straight Lines.pdf',
            'chapter_number': '10',
            'headings': [
                ("10", "Straight Lines"),
                ("10.1", "Introduction"),
                ("10.2", "Slope of a Line"),
                ("10.3", "Various Forms of the Equation of a Line"),
                ("10.4", "General Equation of a Line"),
                ("10.5", "Distance of a Point From a Line"),
            ]
        },
        {
            'subject': 'Maths',
            'class': 'Class 11',
            'chapter_file': 'Conic Sections.pdf',
            'chapter_number': '11',
            'headings': [
                ("11", "Conic Sections"),
                ("11.1", "Introduction"),
                ("11.2", "Sections of a Cone"),
                ("11.3", "Circle"),
                ("11.4", "Parabola"),
                ("11.5", "Ellipse"),
                ("11.6", "Hyperbola"),
            ]
        },
        {
            'subject': 'Maths',
            'class': 'Class 11',
            'chapter_file': 'Introduction to Three Dimensional Geometry.pdf',
            'chapter_number': '12',
            'headings': [
                ("12", "Introduction to Three Dimensional Geometry"),
                ("12.1", "Introduction"),
                ("12.2", "Coordinate Axes and Coordinate Planes in Three Dimensional Space"),
                ("12.3", "Coordinates of a Point in Space"),
                ("12.4", "Distance between Two Points"),
                ("12.5", "Section Formula"),
            ]
        },
        {
            'subject': 'Maths',
            'class': 'Class 11',
            'chapter_file': 'Limits And Derivatives.pdf',
            'chapter_number': '13',
            'headings': [
                ("13", "Limits and Derivatives"),
                ("13.1", "Introduction"),
                ("13.2", "Intuitive Idea of Derivatives"),
                ("13.3", "Limits"),
                ("13.4", "Limits of Trigonometric Functions"),
                ("13.5", "Derivatives"),
            ]
        },
        {
            'subject': 'Maths',
            'class': 'Class 11',
            'chapter_file': 'Statistics.pdf',
            'chapter_number': '15',
            'headings': [
                ("15", "Statistics"),
                ("15.1", "Introduction"),
                ("15.2", "Measures of Dispersion"),
                ("15.3", "Range"),
                ("15.4", "Mean Deviation"),
                ("15.5", "Variance and Standard Deviation"),
                ("15.6", "Analysis of Frequency Distributions"),
            ]
        },
        {
            'subject': 'Maths',
            'class': 'Class 11',
            'chapter_file': 'Probability.pdf',
            'chapter_number': '16',
            'headings': [
                ("16", "Probability"),
                ("16.1", "Introduction"),
                ("16.2", "Random Experiments"),
                ("16.3", "Event"),
                ("16.4", "Axiomatic Approach to Probability"),
            ]
                 },
         
         # Chemistry Class 12
         {
             'subject': 'Chemistry',
             'class': 'Class 12',
             'chapter_file': 'Solutions.pdf',
             'chapter_number': '2',
             'headings': [
                 ("2", "Solutions"),
                 ("2.1", "Types of Solutions"),
                 ("2.2", "Expressing Concentration of Solutions"),
                 ("2.3", "Solubility"),
                 ("2.4", "Vapour Pressure of Liquid Solutions"),
                 ("2.5", "Ideal and Non-ideal Solutions"),
                 ("2.6", "Colligative Properties and Determination of Molar Mass"),
                 ("2.7", "Abnormal Molar Masses"),
                 ("2.1.1", "Solid Solutions"),
                 ("2.1.2", "Liquid Solutions"),
                 ("2.1.3", "Gaseous Solutions"),
                 ("2.2.1", "Mass Percentage"),
                 ("2.2.2", "Volume Percentage"),
                 ("2.2.3", "Mole Fraction"),
                 ("2.2.4", "Molarity"),
                 ("2.2.5", "Molality"),
                 ("2.3.1", "Factors Affecting Solubility"),
                 ("2.3.2", "Solubility of Gases in Liquids"),
                 ("2.3.3", "Solubility of Solids in Liquids"),
                 ("2.4.1", "Vapour Pressure of Pure Liquid"),
                 ("2.4.2", "Vapour Pressure of Solution"),
                 ("2.4.3", "Raoult's Law"),
                 ("2.5.1", "Ideal Solutions"),
                 ("2.5.2", "Non-ideal Solutions"),
                 ("2.5.3", "Positive Deviation"),
                 ("2.5.4", "Negative Deviation"),
                 ("2.6.1", "Relative Lowering of Vapour Pressure"),
                 ("2.6.2", "Elevation of Boiling Point"),
                 ("2.6.3", "Depression of Freezing Point"),
                 ("2.6.4", "Osmotic Pressure"),
                 ("2.7.1", "Association of Solute"),
                 ("2.7.2", "Dissociation of Solute"),
                 ("2.7.3", "Van't Hoff Factor"),
             ]
         },
         {
             'subject': 'Chemistry',
             'class': 'Class 12',
             'chapter_file': 'Electrochemistry.pdf',
             'chapter_number': '3',
             'headings': [
                 ("3", "Electrochemistry"),
                 ("3.1", "Electrochemical Cells"),
                 ("3.2", "Galvanic Cells"),
                 ("3.3", "Nernst Equation"),
                 ("3.4", "Conductance of Electrolytic Solutions"),
                 ("3.5", "Electrolytic Cells and Electrolysis"),
                 ("3.6", "Batteries"),
                 ("3.7", "Fuel Cells"),
                 ("3.8", "Corrosion"),
                 ("3.1.1", "Electrochemical Cell"),
                 ("3.1.2", "Electrode Potential"),
                 ("3.1.3", "Standard Electrode Potential"),
                 ("3.2.1", "Construction of Galvanic Cell"),
                 ("3.2.2", "Working of Galvanic Cell"),
                 ("3.2.3", "Cell Potential"),
                 ("3.3.1", "Nernst Equation Derivation"),
                 ("3.3.2", "Applications of Nernst Equation"),
                 ("3.3.3", "Concentration Cell"),
                 ("3.4.1", "Conductance"),
                 ("3.4.2", "Molar Conductivity"),
                 ("3.4.3", "Equivalent Conductivity"),
                 ("3.4.4", "Kohlrausch's Law"),
                 ("3.5.1", "Electrolytic Cell"),
                 ("3.5.2", "Electrolysis"),
                 ("3.5.3", "Faraday's Laws of Electrolysis"),
                 ("3.6.1", "Primary Batteries"),
                 ("3.6.2", "Secondary Batteries"),
                 ("3.6.3", "Lead Storage Battery"),
                 ("3.6.4", "Nickel-Cadmium Battery"),
                 ("3.7.1", "Fuel Cell Construction"),
                 ("3.7.2", "Hydrogen-Oxygen Fuel Cell"),
                 ("3.7.3", "Applications of Fuel Cells"),
                 ("3.8.1", "Types of Corrosion"),
                 ("3.8.2", "Prevention of Corrosion"),
                 ("3.8.3", "Electrochemical Theory of Corrosion"),
             ]
         },
         {
             'subject': 'Chemistry',
             'class': 'Class 12',
             'chapter_file': 'Chemical Kinetics.pdf',
             'chapter_number': '4',
             'headings': [
                 ("4", "Chemical Kinetics"),
                 ("4.1", "Rate of a Chemical Reaction"),
                 ("4.2", "Factors Influencing Rate of a Reaction"),
                 ("4.3", "Dependence of Rate on Concentration"),
                 ("4.4", "Integrated Rate Equations"),
                 ("4.5", "Pseudo First Order Reactions"),
                 ("4.6", "Temperature Dependence of the Rate of a Reaction"),
                 ("4.7", "Effect of Catalyst"),
                 ("4.8", "Collision Theory of Chemical Reactions"),
                 ("4.1.1", "Average Rate of Reaction"),
                 ("4.1.2", "Instantaneous Rate of Reaction"),
                 ("4.1.3", "Rate of Disappearance"),
                 ("4.1.4", "Rate of Appearance"),
                 ("4.2.1", "Nature of Reactants"),
                 ("4.2.2", "Concentration of Reactants"),
                 ("4.2.3", "Temperature"),
                 ("4.2.4", "Catalyst"),
                 ("4.2.5", "Surface Area"),
                 ("4.3.1", "Rate Law"),
                 ("4.3.2", "Order of Reaction"),
                 ("4.3.3", "Molecularity"),
                 ("4.4.1", "Zero Order Reaction"),
                 ("4.4.2", "First Order Reaction"),
                 ("4.4.3", "Second Order Reaction"),
                 ("4.5.1", "Acid Hydrolysis of Ethyl Acetate"),
                 ("4.5.2", "Inversion of Cane Sugar"),
                 ("4.6.1", "Arrhenius Equation"),
                 ("4.6.2", "Activation Energy"),
                 ("4.6.3", "Effect of Temperature on Rate Constant"),
                 ("4.7.1", "Homogeneous Catalysis"),
                 ("4.7.2", "Heterogeneous Catalysis"),
                 ("4.7.3", "Enzyme Catalysis"),
                 ("4.8.1", "Collision Theory"),
                 ("4.8.2", "Activation Energy Barrier"),
                 ("4.8.3", "Effective Collisions"),
             ]
         },
         {
             'subject': 'Chemistry',
             'class': 'Class 12',
             'chapter_file': 'Surface Chemistry.pdf',
             'chapter_number': '5',
             'headings': [
                 ("5", "Surface Chemistry"),
                 ("5.1", "Adsorption"),
                 ("5.2", "Catalysis"),
                 ("5.3", "Colloids"),
                 ("5.4", "Emulsions"),
                 ("5.1.1", "Physical Adsorption"),
                 ("5.1.2", "Chemical Adsorption"),
                 ("5.1.3", "Factors Affecting Adsorption"),
                 ("5.1.4", "Adsorption Isotherms"),
                 ("5.2.1", "Homogeneous Catalysis"),
                 ("5.2.2", "Heterogeneous Catalysis"),
                 ("5.2.3", "Enzyme Catalysis"),
                 ("5.2.4", "Catalyst Selectivity"),
                 ("5.3.1", "Types of Colloids"),
                 ("5.3.2", "Preparation of Colloids"),
                 ("5.3.3", "Purification of Colloids"),
                 ("5.3.4", "Properties of Colloids"),
                 ("5.4.1", "Types of Emulsions"),
                 ("5.4.2", "Emulsifying Agents"),
                 ("5.4.3", "Applications of Emulsions"),
             ]
         },
         {
             'subject': 'Chemistry',
             'class': 'Class 12',
             'chapter_file': 'General Principles and Processes of Isolation of Elements.pdf',
             'chapter_number': '6',
             'headings': [
                 ("6", "General Principles and Processes of Isolation of Elements"),
                 ("6.1", "Occurrence of Metals"),
                 ("6.2", "Concentration of Ores"),
                 ("6.3", "Extraction of Crude Metal from Concentrated Ore"),
                 ("6.4", "Thermodynamic Principles of Metallurgy"),
                 ("6.5", "Electrochemical Principles of Metallurgy"),
                 ("6.6", "Oxidation and Reduction"),
                 ("6.7", "Refining"),
                 ("6.1.1", "Native State"),
                 ("6.1.2", "Combined State"),
                 ("6.1.3", "Minerals and Ores"),
                 ("6.2.1", "Hydraulic Washing"),
                 ("6.2.2", "Magnetic Separation"),
                 ("6.2.3", "Froth Floatation"),
                 ("6.2.4", "Leaching"),
                 ("6.3.1", "Calcination"),
                 ("6.3.2", "Roasting"),
                 ("6.3.3", "Smelting"),
                 ("6.4.1", "Ellingham Diagram"),
                 ("6.4.2", "Reduction of Metal Oxides"),
                 ("6.4.3", "Reduction of Metal Sulphides"),
                 ("6.5.1", "Electrolytic Reduction"),
                 ("6.5.2", "Electrolytic Refining"),
                 ("6.6.1", "Oxidation"),
                 ("6.6.2", "Reduction"),
                 ("6.6.3", "Redox Reactions"),
                 ("6.7.1", "Distillation"),
                 ("6.7.2", "Liquation"),
                 ("6.7.3", "Zone Refining"),
                 ("6.7.4", "Vapour Phase Refining"),
                 ("6.7.5", "Electrolytic Refining"),
             ]
         },
         {
             'subject': 'Chemistry',
             'class': 'Class 12',
             'chapter_file': 'The p-Block Elements.pdf',
             'chapter_number': '7',
             'headings': [
                 ("7", "The p-Block Elements"),
                 ("7.1", "Group 15 Elements"),
                 ("7.2", "Dinitrogen"),
                 ("7.3", "Ammonia"),
                 ("7.4", "Oxides of Nitrogen"),
                 ("7.5", "Nitric Acid"),
                 ("7.6", "Phosphorus – Allotropic Forms"),
                 ("7.7", "Phosphine"),
                 ("7.8", "Phosphorus Halides"),
                 ("7.9", "Phosphorus Oxides"),
                 ("7.10", "Phosphoric Acid"),
                 ("7.11", "Group 16 Elements"),
                 ("7.12", "Dioxygen"),
                 ("7.13", "Simple Oxides"),
                 ("7.14", "Ozone"),
                 ("7.15", "Sulphur – Allotropic Forms"),
                 ("7.16", "Sulphur Dioxide"),
                 ("7.17", "Oxoacids of Sulphur"),
                 ("7.18", "Sulphuric Acid"),
                 ("7.19", "Group 17 Elements"),
                 ("7.20", "Chlorine"),
                 ("7.21", "Hydrogen Chloride"),
                 ("7.22", "Oxoacids of Halogens"),
                 ("7.23", "Interhalogen Compounds"),
                 ("7.24", "Group 18 Elements"),
                 ("7.1.1", "Electronic Configuration"),
                 ("7.1.2", "Atomic and Ionic Radii"),
                 ("7.1.3", "Ionization Enthalpy"),
                 ("7.1.4", "Electron Gain Enthalpy"),
                 ("7.1.5", "Electronegativity"),
                 ("7.1.6", "Physical Properties"),
                 ("7.1.7", "Chemical Properties"),
                 ("7.2.1", "Preparation of Dinitrogen"),
                 ("7.2.2", "Properties of Dinitrogen"),
                 ("7.2.3", "Uses of Dinitrogen"),
                 ("7.3.1", "Preparation of Ammonia"),
                 ("7.3.2", "Properties of Ammonia"),
                 ("7.3.3", "Uses of Ammonia"),
                 ("7.4.1", "Nitric Oxide"),
                 ("7.4.2", "Nitrogen Dioxide"),
                 ("7.4.3", "Dinitrogen Pentoxide"),
                 ("7.5.1", "Preparation of Nitric Acid"),
                 ("7.5.2", "Properties of Nitric Acid"),
                 ("7.5.3", "Uses of Nitric Acid"),
                 ("7.6.1", "White Phosphorus"),
                 ("7.6.2", "Red Phosphorus"),
                 ("7.6.3", "Black Phosphorus"),
                 ("7.7.1", "Preparation of Phosphine"),
                 ("7.7.2", "Properties of Phosphine"),
                 ("7.7.3", "Uses of Phosphine"),
                 ("7.8.1", "Phosphorus Trichloride"),
                 ("7.8.2", "Phosphorus Pentachloride"),
                 ("7.9.1", "Phosphorus Trioxide"),
                 ("7.9.2", "Phosphorus Pentoxide"),
                 ("7.10.1", "Preparation of Phosphoric Acid"),
                 ("7.10.2", "Properties of Phosphoric Acid"),
                 ("7.10.3", "Uses of Phosphoric Acid"),
                 ("7.11.1", "Electronic Configuration"),
                 ("7.11.2", "Atomic and Ionic Radii"),
                 ("7.11.3", "Ionization Enthalpy"),
                 ("7.11.4", "Electron Gain Enthalpy"),
                 ("7.11.5", "Electronegativity"),
                 ("7.11.6", "Physical Properties"),
                 ("7.11.7", "Chemical Properties"),
                 ("7.12.1", "Preparation of Dioxygen"),
                 ("7.12.2", "Properties of Dioxygen"),
                 ("7.12.3", "Uses of Dioxygen"),
                 ("7.13.1", "Simple Oxides"),
                 ("7.13.2", "Mixed Oxides"),
                 ("7.13.3", "Peroxides"),
                 ("7.14.1", "Preparation of Ozone"),
                 ("7.14.2", "Properties of Ozone"),
                 ("7.14.3", "Uses of Ozone"),
                 ("7.15.1", "Rhombic Sulphur"),
                 ("7.15.2", "Monoclinic Sulphur"),
                 ("7.15.3", "Plastic Sulphur"),
                 ("7.16.1", "Preparation of Sulphur Dioxide"),
                 ("7.16.2", "Properties of Sulphur Dioxide"),
                 ("7.16.3", "Uses of Sulphur Dioxide"),
                 ("7.17.1", "Sulphurous Acid"),
                 ("7.17.2", "Sulphuric Acid"),
                 ("7.17.3", "Peroxodisulphuric Acid"),
                 ("7.18.1", "Contact Process"),
                 ("7.18.2", "Properties of Sulphuric Acid"),
                 ("7.18.3", "Uses of Sulphuric Acid"),
                 ("7.19.1", "Electronic Configuration"),
                 ("7.19.2", "Atomic and Ionic Radii"),
                 ("7.19.3", "Ionization Enthalpy"),
                 ("7.19.4", "Electron Gain Enthalpy"),
                 ("7.19.5", "Electronegativity"),
                 ("7.19.6", "Physical Properties"),
                 ("7.19.7", "Chemical Properties"),
                 ("7.20.1", "Preparation of Chlorine"),
                 ("7.20.2", "Properties of Chlorine"),
                 ("7.20.3", "Uses of Chlorine"),
                 ("7.21.1", "Preparation of Hydrogen Chloride"),
                 ("7.21.2", "Properties of Hydrogen Chloride"),
                 ("7.21.3", "Uses of Hydrogen Chloride"),
                 ("7.22.1", "Hypochlorous Acid"),
                 ("7.22.2", "Chlorous Acid"),
                 ("7.22.3", "Chloric Acid"),
                 ("7.22.4", "Perchloric Acid"),
                 ("7.23.1", "Types of Interhalogen Compounds"),
                 ("7.23.2", "Preparation of Interhalogen Compounds"),
                 ("7.23.3", "Properties of Interhalogen Compounds"),
                 ("7.24.1", "Electronic Configuration"),
                 ("7.24.2", "Atomic and Ionic Radii"),
                 ("7.24.3", "Ionization Enthalpy"),
                 ("7.24.4", "Electron Gain Enthalpy"),
                 ("7.24.5", "Physical Properties"),
                 ("7.24.6", "Chemical Properties"),
             ]
         },
         {
             'subject': 'Chemistry',
             'class': 'Class 12',
             'chapter_file': 'The d and f Block Elements.pdf',
             'chapter_number': '8',
             'headings': [
                 ("8", "The d and f Block Elements"),
                 ("8.1", "Position in the Periodic Table"),
                 ("8.2", "Electronic Configurations of the d-Block Elements"),
                 ("8.3", "General Properties of the Transition Elements (d-Block)"),
                 ("8.4", "Some Important Compounds of Transition Elements"),
                 ("8.5", "The Lanthanoids"),
                 ("8.6", "The Actinoids"),
                 ("8.7", "Some Applications of d and f Block Elements"),
                 ("8.1.1", "d-Block Elements"),
                 ("8.1.2", "f-Block Elements"),
                 ("8.1.3", "Position in Periodic Table"),
                 ("8.2.1", "General Electronic Configuration"),
                 ("8.2.2", "Electronic Configuration of 3d Series"),
                 ("8.2.3", "Electronic Configuration of 4d Series"),
                 ("8.2.4", "Electronic Configuration of 5d Series"),
                 ("8.3.1", "Physical Properties"),
                 ("8.3.2", "Atomic and Ionic Sizes"),
                 ("8.3.3", "Ionization Enthalpies"),
                 ("8.3.4", "Oxidation States"),
                 ("8.3.5", "Trends in the M2+/M Standard Electrode Potentials"),
                 ("8.3.6", "Trends in the M3+/M2+ Standard Electrode Potentials"),
                 ("8.3.7", "Trends in Stability of Higher Oxidation States"),
                 ("8.3.8", "Chemical Reactivity and E° Values"),
                 ("8.3.9", "Magnetic Properties"),
                 ("8.3.10", "Formation of Coloured Ions"),
                 ("8.3.11", "Formation of Complex Compounds"),
                 ("8.3.12", "Catalytic Properties"),
                 ("8.3.13", "Formation of Interstitial Compounds"),
                 ("8.3.14", "Alloy Formation"),
                 ("8.4.1", "Oxides and Oxoanions of Metals"),
                 ("8.4.2", "Potassium Dichromate K2Cr2O7"),
                 ("8.4.3", "Potassium Permanganate KMnO4"),
                 ("8.4.4", "Oxides of 3d Series"),
                 ("8.4.5", "Oxoanions of 3d Series"),
                 ("8.5.1", "Electronic Configurations"),
                 ("8.5.2", "Atomic and Ionic Sizes"),
                 ("8.5.3", "Oxidation States"),
                 ("8.5.4", "General Characteristics"),
                 ("8.5.5", "Chemical Reactivity"),
                 ("8.6.1", "Electronic Configurations"),
                 ("8.6.2", "Atomic and Ionic Sizes"),
                 ("8.6.3", "Oxidation States"),
                 ("8.6.4", "General Characteristics"),
                 ("8.6.5", "Chemical Reactivity"),
                 ("8.7.1", "Applications of d-Block Elements"),
                 ("8.7.2", "Applications of f-Block Elements"),
                 ("8.7.3", "Industrial Applications"),
             ]
         },
         {
             'subject': 'Chemistry',
             'class': 'Class 12',
             'chapter_file': 'Coordination Compounds.pdf',
             'chapter_number': '9',
             'headings': [
                 ("9", "Coordination Compounds"),
                 ("9.1", "Werner's Theory of Coordination Compounds"),
                 ("9.2", "Definitions of Some Important Terms Pertaining to Coordination Compounds"),
                 ("9.3", "Nomenclature of Coordination Compounds"),
                 ("9.4", "Isomerism in Coordination Compounds"),
                 ("9.5", "Bonding in Coordination Compounds"),
                 ("9.6", "Bonding in Metal Carbonyls"),
                 ("9.7", "Stability of Coordination Compounds"),
                 ("9.8", "Importance and Applications of Coordination Compounds"),
                 ("9.1.1", "Postulates of Werner's Theory"),
                 ("9.1.2", "Primary Valency"),
                 ("9.1.3", "Secondary Valency"),
                 ("9.1.4", "Limitations of Werner's Theory"),
                 ("9.2.1", "Coordination Entity"),
                 ("9.2.2", "Central Atom/Ion"),
                 ("9.2.3", "Ligands"),
                 ("9.2.4", "Coordination Number"),
                 ("9.2.5", "Coordination Sphere"),
                 ("9.2.6", "Counter Ions"),
                 ("9.2.7", "Coordination Polyhedron"),
                 ("9.2.8", "Oxidation Number of Central Atom"),
                 ("9.2.9", "Homoleptic and Heteroleptic Complexes"),
                 ("9.3.1", "Naming of Coordination Compounds"),
                 ("9.3.2", "Naming of Ligands"),
                 ("9.3.3", "Naming of Central Atom"),
                 ("9.3.4", "Naming of Counter Ions"),
                 ("9.4.1", "Geometrical Isomerism"),
                 ("9.4.2", "Optical Isomerism"),
                 ("9.4.3", "Linkage Isomerism"),
                 ("9.4.4", "Coordination Isomerism"),
                 ("9.4.5", "Ionisation Isomerism"),
                 ("9.4.6", "Solvate Isomerism"),
                 ("9.5.1", "Valence Bond Theory"),
                 ("9.5.2", "Crystal Field Theory"),
                 ("9.5.3", "Ligand Field Theory"),
                 ("9.6.1", "Formation of Metal Carbonyls"),
                 ("9.6.2", "Bonding in Metal Carbonyls"),
                 ("9.6.3", "Properties of Metal Carbonyls"),
                 ("9.7.1", "Stability Constants"),
                 ("9.7.2", "Factors Affecting Stability"),
                 ("9.7.3", "Chelate Effect"),
                 ("9.8.1", "Applications in Analytical Chemistry"),
                 ("9.8.2", "Applications in Medicine"),
                 ("9.8.3", "Applications in Industry"),
                 ("9.8.4", "Applications in Biology"),
             ]
         },
         {
             'subject': 'Chemistry',
             'class': 'Class 12',
             'chapter_file': 'Haloalkanes And Haloarenes.pdf',
             'chapter_number': '10',
             'headings': [
                 ("10", "Haloalkanes and Haloarenes"),
                 ("10.1", "Classification"),
                 ("10.2", "Nomenclature"),
                 ("10.3", "Nature of C–X Bond"),
                 ("10.4", "Methods of Preparation"),
                 ("10.5", "Physical Properties"),
                 ("10.6", "Chemical Reactions"),
                 ("10.1.1", "Alkyl Halides or Haloalkanes (R–X)"),
                 ("10.1.2", "Allylic Halides"),
                 ("10.1.3", "Benzylic Halides"),
                 ("10.1.4", "Vinylic Halides"),
                 ("10.1.5", "Aryl Halides"),
                 ("10.2.1", "Common Names"),
                 ("10.2.2", "IUPAC Names"),
                 ("10.2.3", "Naming of Haloalkanes"),
                 ("10.2.4", "Naming of Haloarenes"),
                 ("10.3.1", "Bond Length"),
                 ("10.3.2", "Bond Strength"),
                 ("10.3.3", "Bond Polarity"),
                 ("10.4.1", "From Alcohols"),
                 ("10.4.2", "From Hydrocarbons"),
                 ("10.4.3", "Halogen Exchange"),
                 ("10.4.4", "From Alkenes"),
                 ("10.4.5", "From Arenes"),
                 ("10.5.1", "Physical State"),
                 ("10.5.2", "Boiling Points"),
                 ("10.5.3", "Density"),
                 ("10.5.4", "Solubility"),
                 ("10.6.1", "Nucleophilic Substitution Reactions"),
                 ("10.6.2", "Elimination Reactions"),
                 ("10.6.3", "Reaction with Metals"),
                 ("10.6.4", "Reduction"),
                 ("10.6.5", "Reaction with Aryl Halides"),
                 ("10.6.6", "Wurtz Reaction"),
                 ("10.6.7", "Fittig Reaction"),
                 ("10.6.8", "Wurtz-Fittig Reaction"),
                 ("10.6.9", "Reaction with Aryl Halides"),
                 ("10.6.10", "Reaction with Aryl Halides"),
             ]
         },
         {
             'subject': 'Chemistry',
             'class': 'Class 12',
             'chapter_file': 'Alcohol Phenols Ethers.pdf',
             'chapter_number': '11',
             'headings': [
                 ("11", "Alcohols, Phenols and Ethers"),
                 ("11.1", "Classification"),
                 ("11.2", "Nomenclature"),
                 ("11.3", "Structures of Functional Groups"),
                 ("11.4", "Alcohols and Phenols"),
                 ("11.5", "Some Commercially Important Alcohols"),
                 ("11.6", "Ethers"),
                 ("11.1.1", "Alcohols"),
                 ("11.1.2", "Phenols"),
                 ("11.1.3", "Ethers"),
                 ("11.2.1", "Naming of Alcohols"),
                 ("11.2.2", "Naming of Phenols"),
                 ("11.2.3", "Naming of Ethers"),
                 ("11.3.1", "Structure of Alcohols"),
                 ("11.3.2", "Structure of Phenols"),
                 ("11.3.3", "Structure of Ethers"),
                 ("11.4.1", "Preparation of Alcohols"),
                 ("11.4.2", "Preparation of Phenols"),
                 ("11.4.3", "Physical Properties"),
                 ("11.4.4", "Chemical Reactions"),
                 ("11.5.1", "Methanol"),
                 ("11.5.2", "Ethanol"),
                 ("11.5.3", "Uses of Alcohols"),
                 ("11.6.1", "Preparation of Ethers"),
                 ("11.6.2", "Physical Properties of Ethers"),
                 ("11.6.3", "Chemical Reactions of Ethers"),
                 ("11.6.4", "Uses of Ethers"),
             ]
         },
         {
             'subject': 'Chemistry',
             'class': 'Class 12',
             'chapter_file': 'Aldehydes, Ketones And Carboxylic Acid.pdf',
             'chapter_number': '12',
             'headings': [
                 ("12", "Aldehydes, Ketones and Carboxylic Acids"),
                 ("12.1", "Nomenclature and Structure of Carbonyl Group"),
                 ("12.2", "Preparation of Aldehydes and Ketones"),
                 ("12.3", "Physical Properties"),
                 ("12.4", "Chemical Reactions"),
                 ("12.5", "Uses of Aldehydes and Ketones"),
                 ("12.6", "Nomenclature and Structure of Carboxyl Group"),
                 ("12.7", "Methods of Preparation of Carboxylic Acids"),
                 ("12.8", "Physical Properties"),
                 ("12.9", "Chemical Reactions"),
                 ("12.10", "Uses of Carboxylic Acids"),
                 ("12.1.1", "Naming of Aldehydes"),
                 ("12.1.2", "Naming of Ketones"),
                 ("12.1.3", "Structure of Carbonyl Group"),
                 ("12.2.1", "From Alcohols"),
                 ("12.2.2", "From Hydrocarbons"),
                 ("12.2.3", "From Acid Chlorides"),
                 ("12.2.4", "From Nitriles"),
                 ("12.2.5", "From Esters"),
                 ("12.3.1", "Physical State"),
                 ("12.3.2", "Boiling Points"),
                 ("12.3.3", "Solubility"),
                 ("12.4.1", "Nucleophilic Addition Reactions"),
                 ("12.4.2", "Reduction"),
                 ("12.4.3", "Oxidation"),
                 ("12.4.4", "Reactions Due to α-Hydrogen"),
                 ("12.4.5", "Other Reactions"),
                 ("12.5.1", "Uses of Aldehydes"),
                 ("12.5.2", "Uses of Ketones"),
                 ("12.6.1", "Naming of Carboxylic Acids"),
                 ("12.6.2", "Structure of Carboxyl Group"),
                 ("12.7.1", "From Primary Alcohols"),
                 ("12.7.2", "From Aldehydes"),
                 ("12.7.3", "From Alkylbenzenes"),
                 ("12.7.4", "From Nitriles"),
                 ("12.7.5", "From Grignard Reagents"),
                 ("12.7.6", "From Esters"),
                 ("12.8.1", "Physical State"),
                 ("12.8.2", "Boiling Points"),
                 ("12.8.3", "Solubility"),
                 ("12.9.1", "Reactions Involving Cleavage of O–H Bond"),
                 ("12.9.2", "Reactions Involving Cleavage of C–OH Bond"),
                 ("12.9.3", "Reactions Involving –COOH Group"),
                 ("12.9.4", "Substitution Reactions in the Hydrocarbon Part"),
                 ("12.10.1", "Uses of Carboxylic Acids"),
                 ("12.10.2", "Industrial Applications"),
             ]
         },
         {
             'subject': 'Chemistry',
             'class': 'Class 12',
             'chapter_file': 'Amines.pdf',
             'chapter_number': '13',
             'headings': [
                 ("13", "Amines"),
                 ("13.1", "Structure of Amines"),
                 ("13.2", "Classification"),
                 ("13.3", "Nomenclature"),
                 ("13.4", "Preparation of Amines"),
                 ("13.5", "Physical Properties"),
                 ("13.6", "Chemical Reactions"),
                 ("13.7", "Method of Preparation of Diazonium Salts"),
                 ("13.8", "Physical Properties"),
                 ("13.9", "Chemical Reactions"),
                 ("13.10", "Importance of Diazonium Salts in Synthesis of Aromatic Compounds"),
                 ("13.1.1", "Structure of Amines"),
                 ("13.1.2", "Hybridisation"),
                 ("13.1.3", "Bond Angles"),
                 ("13.2.1", "Primary Amines"),
                 ("13.2.2", "Secondary Amines"),
                 ("13.2.3", "Tertiary Amines"),
                 ("13.2.4", "Aromatic Amines"),
                 ("13.3.1", "Common Names"),
                 ("13.3.2", "IUPAC Names"),
                 ("13.3.3", "Naming of Amines"),
                 ("13.4.1", "Reduction of Nitro Compounds"),
                 ("13.4.2", "Ammonolysis of Alkyl Halides"),
                 ("13.4.3", "Reduction of Nitriles"),
                 ("13.4.4", "Reduction of Amides"),
                 ("13.4.5", "Gabriel Phthalimide Synthesis"),
                 ("13.4.6", "Hofmann Bromamide Degradation"),
                 ("13.5.1", "Physical State"),
                 ("13.5.2", "Boiling Points"),
                 ("13.5.3", "Solubility"),
                 ("13.6.1", "Basic Character of Amines"),
                 ("13.6.2", "Reaction with Acids"),
                 ("13.6.3", "Alkylation"),
                 ("13.6.4", "Acylation"),
                 ("13.6.5", "Carbylamine Reaction"),
                 ("13.6.6", "Reaction with Nitrous Acid"),
                 ("13.6.7", "Reaction with Aryl Sulphonyl Chloride"),
                 ("13.6.8", "Electrophilic Substitution"),
                 ("13.7.1", "Diazotisation"),
                 ("13.7.2", "Preparation of Diazonium Salts"),
                 ("13.8.1", "Physical State"),
                 ("13.8.2", "Solubility"),
                 ("13.8.3", "Stability"),
                 ("13.9.1", "Replacement Reactions"),
                 ("13.9.2", "Coupling Reactions"),
                 ("13.9.3", "Reduction"),
                 ("13.10.1", "Sandmeyer Reaction"),
                 ("13.10.2", "Gattermann Reaction"),
                 ("13.10.3", "Balz-Schiemann Reaction"),
                 ("13.10.4", "Coupling Reactions"),
             ]
         },
         {
             'subject': 'Chemistry',
             'class': 'Class 12',
             'chapter_file': 'Biomolecules.pdf',
             'chapter_number': '14',
             'headings': [
                 ("14", "Biomolecules"),
                 ("14.1", "Carbohydrates"),
                 ("14.2", "Proteins"),
                 ("14.3", "Enzymes"),
                 ("14.4", "Vitamins"),
                 ("14.5", "Nucleic Acids"),
                 ("14.6", "Hormones"),
                 ("14.1.1", "Classification of Carbohydrates"),
                 ("14.1.2", "Monosaccharides"),
                 ("14.1.3", "Disaccharides"),
                 ("14.1.4", "Polysaccharides"),
                 ("14.1.5", "Importance of Carbohydrates"),
                 ("14.2.1", "Amino Acids"),
                 ("14.2.2", "Structure of Proteins"),
                 ("14.2.3", "Classification of Proteins"),
                 ("14.2.4", "Denaturation of Proteins"),
                 ("14.2.5", "Importance of Proteins"),
                 ("14.3.1", "Mechanism of Enzyme Action"),
                 ("14.3.2", "Factors Affecting Enzyme Activity"),
                 ("14.3.3", "Classification of Enzymes"),
                 ("14.3.4", "Importance of Enzymes"),
                 ("14.4.1", "Classification of Vitamins"),
                 ("14.4.2", "Fat-soluble Vitamins"),
                 ("14.4.3", "Water-soluble Vitamins"),
                 ("14.4.4", "Importance of Vitamins"),
                 ("14.5.1", "Types of Nucleic Acids"),
                 ("14.5.2", "Chemical Composition of Nucleic Acids"),
                 ("14.5.3", "Structure of Nucleic Acids"),
                 ("14.5.4", "Biological Functions of Nucleic Acids"),
                 ("14.6.1", "Classification of Hormones"),
                 ("14.6.2", "Mechanism of Hormone Action"),
                 ("14.6.3", "Importance of Hormones"),
             ]
         },
         {
             'subject': 'Chemistry',
             'class': 'Class 12',
             'chapter_file': 'Polymers.pdf',
             'chapter_number': '15',
             'headings': [
                 ("15", "Polymers"),
                 ("15.1", "Classification of Polymers"),
                 ("15.2", "Types of Polymerisation Reactions"),
                 ("15.3", "Molecular Mass of Polymers"),
                 ("15.4", "Biodegradable Polymers"),
                 ("15.5", "Polymers of Commercial Importance"),
                 ("15.1.1", "Classification Based on Source"),
                 ("15.1.2", "Classification Based on Structure"),
                 ("15.1.3", "Classification Based on Mode of Polymerisation"),
                 ("15.1.4", "Classification Based on Molecular Forces"),
                 ("15.1.5", "Classification Based on Growth Polymerisation"),
                 ("15.2.1", "Addition Polymerisation"),
                 ("15.2.2", "Condensation Polymerisation"),
                 ("15.2.3", "Copolymerisation"),
                 ("15.3.1", "Number Average Molecular Mass"),
                 ("15.3.2", "Weight Average Molecular Mass"),
                 ("15.3.3", "Polydispersity Index"),
                 ("15.4.1", "Poly β-hydroxybutyrate-co-β-hydroxy valerate (PHBV)"),
                 ("15.4.2", "Nylon 2–nylon 6"),
                 ("15.4.3", "Polyglycolic Acid"),
                 ("15.4.4", "Polylactic Acid"),
                 ("15.5.1", "Natural Rubber"),
                 ("15.5.2", "Synthetic Rubber"),
                 ("15.5.3", "Polyethylene"),
                 ("15.5.4", "Polyvinyl Chloride"),
                 ("15.5.5", "Polystyrene"),
                 ("15.5.6", "Polyacrylonitrile"),
                 ("15.5.7", "Teflon"),
                 ("15.5.8", "Nylon"),
                 ("15.5.9", "Polyesters"),
                 ("15.5.10", "Phenol Formaldehyde"),
                 ("15.5.11", "Urea Formaldehyde"),
                 ("15.5.12", "Melamine Formaldehyde"),
                 ("15.5.13", "Bakelite"),
                 ("15.5.14", "Glyptal"),
                 ("15.5.15", "Polyurethane"),
             ]
         },
         {
             'subject': 'Chemistry',
             'class': 'Class 12',
             'chapter_file': 'Chemistry in Everyday Life.pdf',
             'chapter_number': '16',
             'headings': [
                 ("16", "Chemistry in Everyday Life"),
                 ("16.1", "Drugs and their Classification"),
                 ("16.2", "Drug-Target Interaction"),
                 ("16.3", "Therapeutic Action of Different Classes of Drugs"),
                 ("16.4", "Chemicals in Food"),
                 ("16.5", "Cleansing Agents"),
                 ("16.1.1", "Classification of Drugs"),
                 ("16.1.2", "Drugs Acting on Central Nervous System"),
                 ("16.1.3", "Drugs Acting on Peripheral Nervous System"),
                 ("16.1.4", "Drugs Acting on Cardiovascular System"),
                 ("16.1.5", "Drugs Acting on Gastrointestinal Tract"),
                 ("16.1.6", "Drugs Acting on Respiratory System"),
                 ("16.1.7", "Drugs Acting on Endocrine System"),
                 ("16.1.8", "Drugs Acting on Reproductive System"),
                 ("16.1.9", "Drugs Acting on Immune System"),
                 ("16.1.10", "Drugs Acting on Skin"),
                 ("16.1.11", "Drugs Acting on Eyes"),
                 ("16.1.12", "Drugs Acting on Ears"),
                 ("16.1.13", "Drugs Acting on Nose"),
                 ("16.1.14", "Drugs Acting on Mouth"),
                 ("16.1.15", "Drugs Acting on Throat"),
                 ("16.2.1", "Enzymes as Drug Targets"),
                 ("16.2.2", "Receptors as Drug Targets"),
                 ("16.2.3", "Ion Channels as Drug Targets"),
                 ("16.2.4", "Transport Proteins as Drug Targets"),
                 ("16.2.5", "Nucleic Acids as Drug Targets"),
                 ("16.3.1", "Antacids"),
                 ("16.3.2", "Antihistamines"),
                 ("16.3.3", "Neurologically Active Drugs"),
                 ("16.3.4", "Antimicrobials"),
                 ("16.3.5", "Antifertility Drugs"),
                 ("16.4.1", "Food Additives"),
                 ("16.4.2", "Artificial Sweetening Agents"),
                 ("16.4.3", "Food Preservatives"),
                 ("16.4.4", "Antioxidants"),
                 ("16.4.5", "Edible Colours"),
                 ("16.4.6", "Flavouring Agents"),
                 ("16.5.1", "Soaps"),
                 ("16.5.2", "Synthetic Detergents"),
                 ("16.5.3", "Classification of Synthetic Detergents"),
                 ("16.5.4", "Cleansing Action of Soaps and Detergents"),
             ]
         },
     ]
    
    # Prepare data for CSV
    csv_data = []
    for chapter in all_chapters:
        for heading_number, heading_text in chapter['headings']:
            csv_data.append({
                'subject': chapter['subject'],
                'class': chapter['class'],
                'chapter_file': chapter['chapter_file'],
                'chapter_number': chapter['chapter_number'],
                'heading_number': heading_number,
                'heading_text': heading_text
            })
    
    # Write to the main CSV file
    output_file = "extracted_headings_all_subjects.csv"
    with open(output_file, 'w', newline='', encoding='utf-8') as csvfile:
        fieldnames = ['subject', 'class', 'chapter_file', 'chapter_number', 'heading_number', 'heading_text']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        
        writer.writeheader()
        for row in csv_data:
            writer.writerow(row)
    
    print(f"Successfully populated {output_file} with {len(csv_data)} headings from {len(all_chapters)} chapters")
    print(f"\nChapters added:")
    for chapter in all_chapters:
        print(f"  - {chapter['subject']} {chapter['class']}: {chapter['chapter_file']} ({len(chapter['headings'])} headings)")

def main():
    """Main function to populate all chapters."""
    populate_all_chapters()

if __name__ == '__main__':
    main()
